rovers:
  - id: "001"
    chassis:
      mass: 800 # kg
    power_system:
      battery_capacity: 5200 # mAh
      radioisotope_thermoelectric_generator:
        power: 110 # W
      solar_panel: 
        area: 1.5 # m^2
        efficiency: 0.25
    systems:
      mobility:
        wheels_number: 6
        wheel_torque: 669.77
        wheel_horsepower: 0.023
      
      science:
        slots: 3
    
    damage_model:
      environmental_factors:
        dust: 0.02
        temperature: 0.01
        vibration: 0.005
      failure_modes:
        mechanical: 0.003
        electrical: 0.001
