# Mars Rover Simulation Settings
physics:
  time_scale: 1.0                # Speed of simulation (1.0 = real time)

gameplay:
  # Rover settings
  starting_battery: 100          # Starting battery percentage
  
  default_rover: "001"           # Default rover ID to use in roverConfig.yaml
  default_landingSite: "id"      # Default landing site to use in terrainConfig.json